sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - pip3 install numpy scipy
    - language: python
      os: linux
      python: 3.5
      before_install:
        - pip3 install --upgrade pip
        - pip3 install numpy scipy
        - export CC=gcc-5 CXX=g++-5
install:
  - pip3 install -e .
script:
  - python3 -m unittest discover .
notifications:
  email: false
